### ISSUE TITLE
Support column sorting (bonus: filtering)

### ISSUE THREAD

**Issue by jphorn** [roytanck/rt-plugin-report#16]
Please support column sorting to make it easier to see all "old" plugins together or which plugins have been recently updated. 

Bonus if you could support filtering as well (e.g. show all plugins /w last update > 2 year)

**Comment by Zodiac1978** [comment]
I don't know if this would be some overkill, but TablePress is using https://www.datatables.net/ for sorting and filtering tables which could be used here.

**Comment by roytanck** [comment]
I'd really like to avoid adding a large javacript component just to add sorting. Also, the xls export allows you to sort/filter/etc outside of wp-admin.

**Comment by Zodiac1978** [comment]
Agreed!

Datatables is huge and has many not needed features. But what about a smaller solution? 

Adding sorting to a table seems to be a common task with many solutions. Here is a small list of possible scripts which are just offering more basic operations:
https://ourcodeworld.com/articles/read/619/top-7-best-table-sorter-javascript-and-jquery-plugins

What do you think?

**Comment by Zodiac1978** [comment]
I have played around with [tablesort](https://github.com/tristen/tablesort) – I choosed it, because it was small, still mighty and seems to be still maintained – and now I have a running version in a branch of my fork.

It works great and is really useful. I needed to add `number` and `dotsep` as sorting methods and now almost everything is working. Sorting the individual version is not useful, so I disabled it.

The last remaining problem is the column with "Last update". I think I need to build my own sorting method for this (with day < week < month < year).

I will report back if I have _sorted this out_. Pun intended. ;)

**Comment by Zodiac1978** [comment]
And fixed! I've used the timestamp for sorting :)

https://github.com/Zodiac1978/rt-plugin-report/tree/feature-tablesorting

**Comment by roytanck** [comment]
@Zodiac1978 Just installed the version from your feature branch, and I agree it's useful. More so than I originally thought. Well worth the extra javascript files imho, so thank you for working on this feature. Could you prepare a PR so I can merge your work?

**Comment by Zodiac1978** [comment]
> Could you prepare a PR so I can merge your work?

Yes, of course! :)

I would like to check a few things first. 

Do you want to add the CSS to your file or should this be separated? It is already modified and not the original file form the tablesorter project.

I think we should add the non-minified versions too to comply with the guidelines. I can add them before I create the PR. Just add them in the same folder is okay?

I doesn't make any sense to me to sort the column with the plugin version number, so I disabled sorting there. Fine for you?

**Comment by roytanck** [comment]
Yes, please add the tablesort-related CSS to the plugin's stylesheet. It needs to be loaded on the same screen, so I see no reason to do two separate HTTP calls.

Adding the non-minified files to the same folder is also fine imho. It's not a very crowded folder (yet?) :).

Every plugin has its own version system, so sorting them makes no sense to me. So yes, please keep sorting disabled for that column.

Thanks again!

P.S. I pushed a version 1.6.1 (minor because essentially just bug fixes) to the repo an hour ago, but it's not yet showing on the plugin page. Usually this happens almost instantly. Weird. Anyway, this function will be 1.7.

**Comment by Zodiac1978** [comment]
Adding the non minified version makes not much sense without the build tools, there is another way to comply with the rules:

>     Include the source code in the deployed plugin
>     A link in the readme to the development location

We could also add just a line with a credit (which maybe is necessary by the MIT license)

```
== Credits ==

Special thanks go to [Tristen Forsythe Brown](http://tristen.ca/) for the [tablesort JavaScript library](https://github.com/tristen/tablesort) licensed under the MIT License.
```

**Comment by roytanck** [comment]
@Zodiac1978 That's even better!

**Comment by Zodiac1978** [comment]
Another thought: Shouldn't we start sorting (and showing the export button) if the script is finished with loading all plugin information?

**Comment by roytanck** [comment]
Yes, that seems like a good idea. I think the table will export okay if partially filled, but I don't see a reason to ever want to do that.

The rtpr_process_next_plugin function in the javascript file already checks whether loading is done, so we can call a new function there that adds the export link and initializes the tabel sorting.

**Comment by Zodiac1978** [comment]
Yep, that worked perfectly! I've added it to the PR #31
