### ISSUE TITLE
Sorting broken

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#59]
I saw something strange. The table is sorted by version, but it is not working correct. Need to check what the reason is. Just a heads up!

![Bildschirmfoto 2024-12-03 um 09 04 53](https://github.com/user-attachments/assets/81edaf71-8974-4592-b5ad-cad6b2f6311d)

**Comment by Zodiac1978** [comment]
Okay, I tested a little bit and the `dotsep` sorting does not like text which is not a version number (in my case "Keine Daten verfügbar" - "no data available").

This can be fixed if we add  `data-sort="0"` to the `td` markup if there is no version number for "Tested up to" available.

I can make a PR for this.

**Comment by roytanck** [comment]
Hi Torsten. Thanks for looking into this. A PR would be wonderful.

I'm not sure when I'll be able to do a new release, because there's some confusion about source code copyright for hobby projects at my new job. I'd like to be sure that there's no problem before releasing anything.

Also, the whole wpdrama situation right now is not helping. I've paused all contributions to core, meta and the photo team, but working on 100% plugins also kinda feels like contributing.
